# Generated by Django 5.1.7 on 2025-05-13 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property_model',
            name='area',
            field=models.CharField(default='120', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property_model',
            name='status',
            field=models.CharField(choices=[('ON GOING', 'ON GOING'), ('COMPLETED', 'COMPLETED')], default='ON GOING', max_length=100),
            preserve_default=False,
        ),
    ]
