# Generated by Django 5.1.7 on 2025-05-13 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_property_model_area_property_model_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property_model',
            name='client_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
