# Generated by Django 5.1.7 on 2025-05-13 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_property_model_client_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hiring',
            name='position',
            field=models.CharField(choices=[('architect', 'Architect'), ('junior_architect', 'Junior Architect'), ('interior_designer', 'Interior Designer'), ('3d_visualizer', '3D Visualizer'), ('project_manager', 'Project Manager'), ('site_engineer', 'Site Engineer'), ('urban_planner', 'Urban Planner'), ('draughtsman', 'Draughtsman'), ('bim_specialist', 'BIM Specialist'), ('landscape_architect', 'Landscape Architect'), ('civil_engineer', 'Civil Engineer'), ('structural_engineer', 'Structural Engineer'), ('admin_staff', 'Admin Staff')], max_length=100),
        ),
    ]
