# Generated by Django 5.1.4 on 2025-05-14 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_hiring_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hiring',
            name='position',
            field=models.CharField(choices=[('architect', 'Architect'), ('junior_architect', 'Junior Architect'), ('interior_designer', 'Interior Designer'), ('3d_visualizer', '3D Visualizer'), ('project_manager', 'Project Manager'), ('site_engineer', 'Site Engineer'), ('draftsman_civil', 'Draftsman Civil'), ('quantity_surveyor', 'Quantity Surveyor')], default='architect', max_length=100),
        ),
    ]
